### ISSUE TITLE
i'm having this error to compile on ubuntu 16.04

### ISSUE THREAD

**Issue by ciscoaofran** [irllabs/ml-lib#169]
find: "../vendor/grt/GRT": Arquivo ou diretório não encontrado
g++ -Wno-error -fPIC -O2 -std=c++11 -fdata-sections -ffunction-sections  -I../vendor/flext/source -I../vendor/grt/GRT -I../vendor/pd -I../sources -DFLEXT_INLINE -DFLEXT_SYS_PD -DFLEXT_USE_CMEM -DFLEXT_ATTRIBUTES=1 -DFLEXT_USE_HEX_SETUP_NAME -DPD -c ../sources/classification/ml_adaboost.cpp -o ../sources/classification/ml_adaboost.o
In file included from ../sources/ml_ml.h:23:0,
                 from ../sources/classification/ml_classification.h:22,
                 from ../sources/classification/ml_adaboost.cpp:19:
../sources/ml_base.h:30:19: fatal error: flext.h: Arquivo ou diretório não encontrado
 #include "flext.h"
                   ^
compilation terminated.
Makefile:114: recipe for target '../sources/classification/ml_adaboost.o' failed
make: *** [../sources/classification/ml_adaboost.o] Error 1

**Comment by NiccoloGranieri** [comment]
Hi @ciscoaofran! Are you still encountering this issue or did you manage to solve it? If the issue is still present, could you provide us with a bit more info? Thanks.
